### ISSUE TITLE
PHP version requirement unclear

### ISSUE THREAD

**Issue by ahungry** [mkrauss/ticc#1]
Should mention required PHP version in the README (the version of `functional` required depends on PHP 5.6), although it looks like some of the code would depend on PHP 7 features (unless string typecast works for closures, but I think thats a PHP 7 feature right?), as well as include the minimum required PHP version in the composer lockfile.

**Comment by mkrauss** [comment]
By "string typecast" I think you are referring to the type declarations? If that's the only thing making this require PHP 7, I would not be opposed to taking them out... What do you think? Is supporting older PHPs valuable for this?

**Comment by ahungry** [comment]
I like PHP7 and in the PR earlier I added it to the readme so its clear for everyone (even installing on an old thing like Ubuntu 14.04 isn't hard in the /opt directory) so I say, onward with PHP7!
